// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEREADERPLUGINEXPORT_H
#define VISTALDATAIMAGEREADERPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalDataImageReaderPlugin_EXPORTS
        #define VISTALDATAIMAGEREADERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALDATAIMAGEREADERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALDATAIMAGEREADERPLUGIN_EXPORT
#endif

#endif
