// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSSEGMENTATIONPLUGIN_H
#define VISTALPROCESSSEGMENTATIONPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalProcessSegmentationSTREMPluginExport.h"

class VISTALPROCESSSEGMENTATIONSTREMPLUGIN_EXPORT vistalProcessSegmentationSTREMPluginPrivate;

class VISTALPROCESSSEGMENTATIONSTREMPLUGIN_EXPORT vistalProcessSegmentationSTREMPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalProcessSegmentationSTREMPlugin(QObject *parent = 0);
    ~vistalProcessSegmentationSTREMPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vistalProcessSegmentationSTREMPluginPrivate *d;
};

#endif
