// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSSEGMENTATION_H
#define VISTALPROCESSSEGMENTATION_H

#include <dtkCore/dtkAbstractProcess.h>

#include "vistalProcessSegmentationPluginExport.h"
#include "Image3D.hh"

class vistalProcessSegmentationPrivate;
class dtkAbstractData;

/**
* @class vistalProcessSegmentation
* @brief Image segmentation based on the GraphCuts method
* @TODO Input/Output type conversions
* @TODO Only use method setInput
**/

class VISTALPROCESSSEGMENTATIONPLUGIN_EXPORT vistalProcessSegmentation : public dtkAbstractProcess
{
    Q_OBJECT

public:
             vistalProcessSegmentation(void);
    virtual ~vistalProcessSegmentation(void);

    virtual QString description(void) const;

    static bool registered(void);

public slots:

    void setInput(dtkAbstractData *data, int channel);

    void setParameter(double  data, int channel);

    int update(void);

    dtkAbstractData *output(void);

private:
    vistalProcessSegmentationPrivate *d;
};

dtkAbstractProcess *createVistalProcessSegmentation(void);

#endif
