// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMASYMMETRYPLANETOOLBOX_H
#define ANIMASYMMETRYPLANETOOLBOX_H

#include <medToolBoxFilteringCustom.h>
#include "animaSymmetryPlanePluginExport.h"

class animaSymmetryPlaneToolBoxPrivate;

class ANIMASYMMETRYPLANEPLUGIN_EXPORT animaSymmetryPlaneToolBox : public medToolBoxFilteringCustom
{
    Q_OBJECT

public:
    animaSymmetryPlaneToolBox(QWidget *parent = 0);
    ~animaSymmetryPlaneToolBox(void);

    dtkAbstractData *processOutput();

    static bool registered(void);

signals:
    void success(void);
    void failure(void);

public slots:
    void run(void);
    void saveRealignTransformFile(void);
    void saveTransformFile(void);
    void setSuccess(void);
    void updateMetric(int);

private:
    animaSymmetryPlaneToolBoxPrivate *d;

};

#endif
