// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMASYMMETRYPLANEPLUGIN_H
#define ANIMASYMMETRYPLANEPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "animaSymmetryPlanePluginExport.h"

class ANIMASYMMETRYPLANEPLUGIN_EXPORT animaSymmetryPlanePluginPrivate;

class ANIMASYMMETRYPLANEPLUGIN_EXPORT animaSymmetryPlanePlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)
    
public:
    animaSymmetryPlanePlugin(QObject *parent = 0);
    ~animaSymmetryPlanePlugin(void);
    
    virtual bool initialize(void);
    virtual bool uninitialize(void);
    
    virtual QString name(void) const;
    virtual QString identifier(void) const;
    virtual QString description(void) const;
    virtual QString contact(void) const;
    virtual QString version (void) const;
    virtual QStringList authors(void) const;
    virtual QStringList contributors(void) const;
    virtual QStringList dependencies(void) const;
    
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;
    
private:
    animaSymmetryPlanePluginPrivate *d;
};

#endif
