// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef animaNonLocalMeansFilter_H
#define animaNonLocalMeansFilter_H

#include <dtkCore/dtkAbstractProcess.h>

#include "animaNonLocalMeansFilterPluginExport.h"

class animaNonLocalMeansFilterPrivate;

class ANIMANONLOCALMEANSFILTERPLUGIN_EXPORT animaNonLocalMeansFilter : public dtkAbstractProcess
{
    Q_OBJECT

public:
    animaNonLocalMeansFilter(void);
    virtual ~animaNonLocalMeansFilter(void);

    virtual QString description(void) const;

    void emitProgressed(int progression);

    static bool registered(void);


public slots:

    //! Input data to the plugin is set through here
    void setInput(dtkAbstractData *data);

    //! Parameters are set through here, channel allows to handle multiple parameters
    void setParameter(double  data, int channel);

    //! Method to actually start the filter
    int update(void);

    //! The output will be available through here
    dtkAbstractData *output(void);



private:
    animaNonLocalMeansFilterPrivate *d;

};

dtkAbstractProcess *createanimaNonLocalMeansFilter(void);

#endif
