// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "medtkNLMeansDiffusion.h"
#include "medtkNLMeansDiffusionPlugin.h"
#include "medtkNLMeansDiffusionToolBox.h"

#include <dtkLog/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// medtkNLMeansDiffusionPluginPrivate
// /////////////////////////////////////////////////////////////////

class medtkNLMeansDiffusionPluginPrivate
{
public:
    // Class variables go here.
    static const char *s_Name;
};

const char * medtkNLMeansDiffusionPluginPrivate::s_Name = "medtkNLMeansDiffusion";

// /////////////////////////////////////////////////////////////////
// medtkNLMeansDiffusionPlugin
// /////////////////////////////////////////////////////////////////

medtkNLMeansDiffusionPlugin::medtkNLMeansDiffusionPlugin(QObject *parent) : dtkPlugin(parent), d(new medtkNLMeansDiffusionPluginPrivate)
{
    
}

medtkNLMeansDiffusionPlugin::~medtkNLMeansDiffusionPlugin(void)
{
    delete d;
    
    d = NULL;
}

bool medtkNLMeansDiffusionPlugin::initialize(void)
{
    if(!medtkNLMeansDiffusion::registered())
        dtkWarn() << "Unable to register medtkNLMeansDiffusion type";
    
    if ( !medtkNLMeansDiffusionToolBox::registered() )
        dtkWarn() << "Unable to register medtkNLMeansDiffusion toolbox";
    
    return true;
}

bool medtkNLMeansDiffusionPlugin::uninitialize(void)
{
    return true;
}

QString medtkNLMeansDiffusionPlugin::name(void) const
{
    return "medtkNLMeansDiffusionPlugin";
}

QString medtkNLMeansDiffusionPlugin::description(void) const
{
    return tr("Non Local Means denosing filter for diffusion images.");
}

QString medtkNLMeansDiffusionPlugin::version(void) const
{
    return MEDTKNLMEANSDIFFUSIONPLUGIN_VERSION;
}

QString medtkNLMeansDiffusionPlugin::contact(void) const
{
    return "";
}

QStringList medtkNLMeansDiffusionPlugin::authors(void) const
{
    QStringList list;
    return list;
}

QStringList medtkNLMeansDiffusionPlugin::contributors(void) const
{
    QStringList list;
    return list;
}

QString medtkNLMeansDiffusionPlugin::identifier(void) const
{
    return medtkNLMeansDiffusionPluginPrivate::s_Name;
}


QStringList medtkNLMeansDiffusionPlugin::tags(void) const
{
    return QStringList();
}

QStringList medtkNLMeansDiffusionPlugin::types(void) const
{
    return QStringList() << "medtkNLMeansDiffusion";
}
QStringList medtkNLMeansDiffusionPlugin::dependencies(void) const
{
    return QStringList();
}
Q_EXPORT_PLUGIN2(medtkNLMeansDiffusionPlugin, medtkNLMeansDiffusionPlugin)
