// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "animaNonLocalMeansFilter.h"
#include "animaNonLocalMeansFilterPlugin.h"
#include "animaNonLocalMeansFilterToolBox.h"

#include <dtkLog/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// animaNonLocalMeansFilterPluginPrivate
// /////////////////////////////////////////////////////////////////

class animaNonLocalMeansFilterPluginPrivate
{
public:
    // Class variables go here.
    static const char *s_Name;
};

const char * animaNonLocalMeansFilterPluginPrivate::s_Name = "animaNonLocalMeansFilter";

// /////////////////////////////////////////////////////////////////
// animaNonLocalMeansFilterPlugin
// /////////////////////////////////////////////////////////////////

animaNonLocalMeansFilterPlugin::animaNonLocalMeansFilterPlugin(QObject *parent) : dtkPlugin(parent), d(new animaNonLocalMeansFilterPluginPrivate)
{

}

animaNonLocalMeansFilterPlugin::~animaNonLocalMeansFilterPlugin(void)
{
    delete d;

    d = NULL;
}

bool animaNonLocalMeansFilterPlugin::initialize(void)
{
    if(!animaNonLocalMeansFilter::registered())
        dtkWarn() << "Unable to register animaNonLocalMeansFilter type";

    if ( !animaNonLocalMeansFilterToolBox::registered() )
        dtkWarn() << "Unable to register animaNonLocalMeansFilter toolbox";

    return true;
}

bool animaNonLocalMeansFilterPlugin::uninitialize(void)
{
    return true;
}

QString animaNonLocalMeansFilterPlugin::name(void) const
{
    return "animaNonLocalMeansFilterPlugin";
}

QString animaNonLocalMeansFilterPlugin::description(void) const
{
    return tr("Non Local Means denosing filter for diffusion images.");
}

QString animaNonLocalMeansFilterPlugin::version(void) const
{
    return ANIMANONLOCALMEANSFILTERPLUGIN_VERSION;
}

QString animaNonLocalMeansFilterPlugin::contact(void) const
{
    return "";
}

QStringList animaNonLocalMeansFilterPlugin::authors(void) const
{
    QStringList list;
    return list;
}

QStringList animaNonLocalMeansFilterPlugin::contributors(void) const
{
    QStringList list;
    return list;
}

QString animaNonLocalMeansFilterPlugin::identifier(void) const
{
    return animaNonLocalMeansFilterPluginPrivate::s_Name;
}


QStringList animaNonLocalMeansFilterPlugin::tags(void) const
{
    return QStringList();
}

QStringList animaNonLocalMeansFilterPlugin::types(void) const
{
    return QStringList() << "animaNonLocalMeansFilter";
}
QStringList animaNonLocalMeansFilterPlugin::dependencies(void) const
{
    return QStringList();
}
Q_EXPORT_PLUGIN2(animaNonLocalMeansFilterPlugin, animaNonLocalMeansFilterPlugin)
