// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDTKNLMEANSDIFFUSION_H
#define MEDTKNLMEANSDIFFUSION_H

#include <dtkCore/dtkAbstractProcess.h>

#include "medtkNLMeansDiffusionPluginExport.h"

class medtkNLMeansDiffusionPrivate;

class MEDTKNLMEANSDIFFUSIONPLUGIN_EXPORT medtkNLMeansDiffusion : public dtkAbstractProcess
{
    Q_OBJECT
    
public:
    medtkNLMeansDiffusion(void);
    virtual ~medtkNLMeansDiffusion(void);
    
    virtual QString description(void) const;
    
    static bool registered(void);
    
public slots:
    
    //! Input data to the plugin is set through here
    void setInput(dtkAbstractData *data);
    
    //! Parameters are set through here, channel allows to handle multiple parameters
    void setParameter(double  data, int channel);
    
    //! Method to actually start the filter
    int update(void);
    
    //! The output will be available through here
    dtkAbstractData *output(void);
    
    
private:
    medtkNLMeansDiffusionPrivate *d;
};

dtkAbstractProcess *createMedtkNLMeansDiffusion(void);

#endif
