// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMANONLOCALMEANSFILTERPLUGINEXPORT_H
#define ANIMANONLOCALMEANSFILTERPLUGINEXPORT_H

#ifdef WIN32
    #ifdef medtkNLMeansDiffusionPlugin_EXPORTS
        #define ANIMANONLOCALMEANSFILTERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ANIMANONLOCALMEANSFILTERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ANIMANONLOCALMEANSFILTERPLUGIN_EXPORT
#endif

#endif
