// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMANONLOCALMEANSFILTERTOOLBOX_H
#define ANIMANONLOCALMEANSFILTERTOOLBOX_H

#include <medFilteringAbstractToolBox.h>
#include "animaNonLocalMeansFilterPluginExport.h"

class animaNonLocalMeansFilterToolBoxPrivate;

class ANIMANONLOCALMEANSFILTERPLUGIN_EXPORT animaNonLocalMeansFilterToolBox : public medFilteringAbstractToolBox
{
    Q_OBJECT

public:
    animaNonLocalMeansFilterToolBox(QWidget *parent = 0);
    ~animaNonLocalMeansFilterToolBox(void);

    dtkAbstractData *processOutput();
    dtkPlugin* plugin();

    static bool registered(void);

signals:
    void success(void);
    void failure(void);

    public slots:
    void run(void);
    void update(dtkAbstractView *view);

private:
    animaNonLocalMeansFilterToolBoxPrivate *d;
};

#endif
