// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDTKNLMEANSDIFFUSIONTOOLBOX_H
#define MEDTKNLMEANSDIFFUSIONTOOLBOX_H

#include <medToolBoxFilteringCustom.h>
#include "medtkNLMeansDiffusionPluginExport.h"

class medtkNLMeansDiffusionToolBoxPrivate;

class MEDTKNLMEANSDIFFUSIONPLUGIN_EXPORT medtkNLMeansDiffusionToolBox : public medToolBoxFilteringCustom
{
    Q_OBJECT
    
public:
    medtkNLMeansDiffusionToolBox(QWidget *parent = 0);
    ~medtkNLMeansDiffusionToolBox(void);
    
    dtkAbstractData *processOutput();
    
    static bool registered(void);
    
signals:
    void success(void);
    void failure(void);
    
    public slots:
    void run(void);
    
private:
    medtkNLMeansDiffusionToolBoxPrivate *d;
};

#endif
