// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDTKNLMEANSDIFFUSIONPLUGIN_H
#define MEDTKNLMEANSDIFFUSIONPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "medtkNLMeansDiffusionPluginExport.h"

class MEDTKNLMEANSDIFFUSIONPLUGIN_EXPORT medtkNLMeansDiffusionPluginPrivate;

class MEDTKNLMEANSDIFFUSIONPLUGIN_EXPORT medtkNLMeansDiffusionPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)
    
public:
    medtkNLMeansDiffusionPlugin(QObject *parent = 0);
    ~medtkNLMeansDiffusionPlugin(void);
    
    virtual bool initialize(void);
    virtual bool uninitialize(void);
    
    virtual QString name(void) const;
    virtual QString identifier(void) const;
    virtual QString description(void) const;
    virtual QString contact(void) const;
    virtual QString version (void) const;
    virtual QStringList authors(void) const;
    virtual QStringList contributors(void) const;
    virtual QStringList dependencies(void) const;
    
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;
    
private:
    medtkNLMeansDiffusionPluginPrivate *d;
};

#endif
