// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSSEGMENTATIONGCEMPLUGINEXPORT_H
#define VISTALPROCESSSEGMENTATIONGCEMPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalProcessSegmentationStremPlugin_EXPORTS
        #define VISTALPROCESSSEGMENTATIONGCEMPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALPROCESSSEGMENTATIONGCEMPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALPROCESSSEGMENTATIONGCEMPLUGIN_EXPORT
#endif

#endif
