// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "vistalProcessSegmentationSTREM.h"
#include "vistalProcessSegmentationSTREMPlugin.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// vistalProcessSegmentationPluginPrivate
// /////////////////////////////////////////////////////////////////

class vistalProcessSegmentationSTREMPluginPrivate 
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// vistalProcessSegmentationSTREMPlugin
// /////////////////////////////////////////////////////////////////

vistalProcessSegmentationSTREMPlugin::vistalProcessSegmentationSTREMPlugin(QObject *parent) : dtkPlugin(parent), d(new vistalProcessSegmentationSTREMPluginPrivate)
{

}

vistalProcessSegmentationSTREMPlugin::~vistalProcessSegmentationSTREMPlugin(void)
{
    delete d;

    d = NULL;
}

bool vistalProcessSegmentationSTREMPlugin::initialize(void)
{
    if(!vistalProcessSegmentationSTREM::registered())
	dtkWarning() << "Unable to register vistalProcessSegmentationSTREM type";

    return true;
}

bool vistalProcessSegmentationSTREMPlugin::uninitialize(void)
{
    return true;
}

QString vistalProcessSegmentationSTREMPlugin::name(void) const
{
    return "vistalProcessSegmentationSTREMPlugin";
}

QString vistalProcessSegmentationSTREMPlugin::description(void) const
{
    return "Process for MS Lesion segmentation using multimodal images and robust (trimmed estimator) EM approach";
}

QStringList vistalProcessSegmentationSTREMPlugin::tags(void) const
{
    return QStringList();
}

QStringList vistalProcessSegmentationSTREMPlugin::types(void) const
{
    return QStringList() << "vistalProcessSegmentationSTREM";
}

Q_EXPORT_PLUGIN2(vistalProcessSegmentationSTREMPlugin, vistalProcessSegmentationSTREMPlugin)
