// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "qtshanoirDataSource.h"
#include "qtshanoirDataSourcePlugin.h"
#include "qtshanoirDataSourceToolBox.h"

#include <dtkLog/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// qtshanoirDataSourcePluginPrivate
// /////////////////////////////////////////////////////////////////

class qtshanoirDataSourcePluginPrivate 
{
public:
  // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// qtshanoirDataSourcePlugin
// /////////////////////////////////////////////////////////////////

qtshanoirDataSourcePlugin::qtshanoirDataSourcePlugin(QObject *parent) : dtkPlugin(parent), d(new qtshanoirDataSourcePluginPrivate)
{
    Q_INIT_RESOURCE(qtshanoir);
}

qtshanoirDataSourcePlugin::~qtshanoirDataSourcePlugin(void)
{
  delete d;
  
  d = NULL;
}

bool qtshanoirDataSourcePlugin::initialize(void)
{
  if(!qtshanoirDataSource::registered())
  {
    dtkWarn() << "Unable to register qtshanoirDataSource type";
  }
  
  return true;
}

bool qtshanoirDataSourcePlugin::uninitialize(void)
{
  return true;
}

QString qtshanoirDataSourcePlugin::name(void) const
{
  return "qtshanoirDataSourcePlugin";
}

QString qtshanoirDataSourcePlugin::description(void) const
{
  return "Shanoir data source plugin";
}

QStringList qtshanoirDataSourcePlugin::authors ( void ) const
{
    return QStringList() << "Olivier Commowick <Olivier.Commowick@inria.fr>";
}

QString qtshanoirDataSourcePlugin::contact ( void ) const
{
    return "Olivier.Commowick@inria.fr";
}

QStringList qtshanoirDataSourcePlugin::contributors ( void ) const
{
    return QStringList() << "Alexandre Abadie <Alexandre.Abadie@inria.fr>"
                         << QString::fromUtf8("Clément Philipot <clement.philipot@inria.fr>")
                         << "Guillaume Renard <Guillaume.Renard@inria.fr>";
}

QStringList qtshanoirDataSourcePlugin::dependencies ( void ) const
{
    return QStringList() << "QtShanoir v1.0";
}

QString qtshanoirDataSourcePlugin::version ( void ) const
{
    return QTSHANOIRDATASOURCEPLUGIN_VERSION;
}

QStringList qtshanoirDataSourcePlugin::tags(void) const
{
  return QStringList() << "shanoir" << "data" << "source";
}

QStringList qtshanoirDataSourcePlugin::types(void) const
{
  return QStringList() << "qtshanoirDataSource";
}

//Q_EXPORT_PLUGIN2(qtshanoirDataSourcePlugin, qtshanoirDataSourcePlugin)
