// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef QTSHANOIRDATASOURCE_H
#define QTSHANOIRDATASOURCE_H

#include <medCore/medAbstractSourceDataPlugin.h>

#include "qtshanoirDataSourcePluginExport.h"

class qtshanoirDataSourcePrivate;
class QtShanoirTreeWidget;

class QTSHANOIRDATASOURCEPLUGIN_EXPORT qtshanoirDataSource : public medAbstractSourceDataPlugin
{
    Q_OBJECT

public:
             qtshanoirDataSource(void);
	    ~qtshanoirDataSource(void);

    QString description(void) const;

    static bool registered(void);
    
    QWidget *widget();
    QWidget *sourceSelectorWidget();
    QString tabName();
    
signals:
     void importedSuccess(void);   
	
public slots:
    void find(void);
    void onImportData(void);   
    void onDownloadFinished(QString fileName);
    
private:
    qtshanoirDataSourcePrivate *d;
    void initWidgets(void);
};

medAbstractSourceDataPlugin *createQtshanoirDataSource(void);

#endif

