// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <dtkCoreSupport/dtkPlugin.h>

#include "qtshanoirDataSourcePluginExport.h"

class QTSHANOIRDATASOURCEPLUGIN_EXPORT qtshanoirDataSourcePluginPrivate;

class QTSHANOIRDATASOURCEPLUGIN_EXPORT qtshanoirDataSourcePlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)
    Q_PLUGIN_METADATA(IID "fr.inria.qtshanoirDataSourcePlugin" FILE "qtshanoirDataSourcePlugin.json")

public:
     qtshanoirDataSourcePlugin(QObject *parent = 0);
    ~qtshanoirDataSourcePlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;
    virtual QString version(void) const;
    virtual QString contact(void) const;
    virtual QStringList authors(void) const;
    virtual QStringList contributors(void) const;
    virtual QStringList dependencies(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     qtshanoirDataSourcePluginPrivate *d;
};
