// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef QTSHANOIRDATASOURCEPLUGIN_H
#define QTSHANOIRDATASOURCEPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "qtshanoirDataSourcePluginExport.h"

class QTSHANOIRDATASOURCEPLUGIN_EXPORT qtshanoirDataSourcePluginPrivate;

class QTSHANOIRDATASOURCEPLUGIN_EXPORT qtshanoirDataSourcePlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     qtshanoirDataSourcePlugin(QObject *parent = 0);
    ~qtshanoirDataSourcePlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     qtshanoirDataSourcePluginPrivate *d;
};

#endif
