// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMALESIONSSEGMENTATIONPLUGINEXPORT_H
#define ANIMALESIONSSEGMENTATIONPLUGINEXPORT_H

#ifdef WIN32
    #ifdef ANIMALESIONSSEGMENTATIONPlugin_EXPORTS
        #define ANIMALESIONSSEGMENTATIONPLUGIN_EXPORT __declspec(dllexport)
    #else
        #define ANIMALESIONSSEGMENTATIONPLUGIN_EXPORT __declspec(dllimport)
    #endif
#else
    #define ANIMALESIONSSEGMENTATIONPLUGIN_EXPORT
#endif

#endif
