// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSDENOISINGPLUGIN_H
#define VISTALPROCESSDENOISINGPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalProcessDenoisingPluginExport.h"

class VISTALPROCESSDENOISINGPLUGIN_EXPORT vistalProcessDenoisingPluginPrivate;

class VISTALPROCESSDENOISINGPLUGIN_EXPORT vistalProcessDenoisingPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalProcessDenoisingPlugin(QObject *parent = 0);
    ~vistalProcessDenoisingPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString contact(void) const;
    virtual QString name(void) const;
    virtual QString description(void) const;
    virtual QString version(void) const;
    virtual QStringList authors(void) const;
    virtual QStringList contributors(void) const;
    virtual QStringList dependencies(void) const;
    
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vistalProcessDenoisingPluginPrivate *d;
};

#endif
