// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "vistalProcessDenoising.h"
#include "vistalProcessDenoisingPlugin.h"
#include "vistalProcessDenoisingToolBox.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// vistalProcessDenoisingPluginPrivate
// /////////////////////////////////////////////////////////////////

class vistalProcessDenoisingPluginPrivate 
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// vistalProcessDenoisingPlugin
// /////////////////////////////////////////////////////////////////

vistalProcessDenoisingPlugin::vistalProcessDenoisingPlugin(QObject *parent) : dtkPlugin(parent), d(new vistalProcessDenoisingPluginPrivate)
{

}

vistalProcessDenoisingPlugin::~vistalProcessDenoisingPlugin(void)
{
    delete d;

    d = NULL;
}

bool vistalProcessDenoisingPlugin::initialize(void)
{
    if(!vistalProcessDenoising::registered())
	dtkWarning() << "Unable to register vistalProcessDenoising type";
    
    if(!vistalProcessDenoisingToolBox::registered())
	dtkWarning() << "Unable to register vistalProcessDenoising toolbox";

    return true;
}

bool vistalProcessDenoisingPlugin::uninitialize(void)
{
    return true;
}

QString vistalProcessDenoisingPlugin::name(void) const
{
    return "vistalProcessDenoisingNLMEANSPlugin";
}

QString vistalProcessDenoisingPlugin::description(void) const
{
    return "NLMeans Denoising Plugin";
}

QStringList vistalProcessDenoisingPlugin::tags(void) const
{
    return QStringList() << "vistal" << "process" << "nlmeans" << "denoising" << "preprocessing";
}

QStringList vistalProcessDenoisingPlugin::types(void) const
{
    return QStringList() << "vistalProcessDenoising";
}

Q_EXPORT_PLUGIN2(vistalProcessDenoisingPlugin, vistalProcessDenoisingPlugin)
