// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGECONVERTERPLUGINEXPORT_H
#define VISTALDATAIMAGECONVERTERPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalDataImageConverterPlugin_EXPORTS
        #define VISTALDATAIMAGECONVERTERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALDATAIMAGECONVERTERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALDATAIMAGECONVERTERPLUGIN_EXPORT
#endif

#endif
