// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "vistalDataImageToItkDataImageSInt3Converter.h"
#include "itkImage3D.hh"
#include "Image3D.hh"

#include <dtkCore/dtkAbstractData.h>
#include <dtkCore/dtkAbstractDataFactory.h>

// /////////////////////////////////////////////////////////////////
// vistalDataImageToItkDataImageSInt3ConverterPrivate
// /////////////////////////////////////////////////////////////////

class vistalDataImageToItkDataImageSInt3ConverterPrivate
{
    public:
        itkImage3D<int> * SInt3Converter;

        dtkAbstractData * output;

};

// /////////////////////////////////////////////////////////////////
// vistalDataImageToItkDataImageSInt3Converter
// /////////////////////////////////////////////////////////////////

vistalDataImageToItkDataImageSInt3Converter::vistalDataImageToItkDataImageSInt3Converter(void) :
    dtkAbstractDataConverter(), d(new vistalDataImageToItkDataImageSInt3ConverterPrivate)
{
    d->output = dtkAbstractDataFactory::instance()->create("itkDataImageInt3");

    d->SInt3Converter = NULL;
}

vistalDataImageToItkDataImageSInt3Converter::~vistalDataImageToItkDataImageSInt3Converter(void)
{

}

bool
vistalDataImageToItkDataImageSInt3Converter::registered(void)
{
    return dtkAbstractDataFactory::instance()->registerDataConverterType("vistalDataImageToItkDataImageSInt3Converter", QStringList() << "vistalDataImageSInt3", "itkDataImageInt3", createVistalDataImageToItkDataImageSInt3Converter);
}

QString
vistalDataImageToItkDataImageSInt3Converter::description(void) const
{
    return "vistalDataImageToItkDataImageSInt3Converter";
}

QStringList
vistalDataImageToItkDataImageSInt3Converter::fromTypes(void) const
{
    return QStringList() << "vistalDataImageSInt3";
}

QString
vistalDataImageToItkDataImageSInt3Converter::toType(void) const
{
    return "itkDataImageInt3";
}

dtkAbstractData *
vistalDataImageToItkDataImageSInt3Converter::convert(void)
{
    if (!d->output)
        return NULL;

    dtkAbstractData *data = this->data();
    if (!data)
        return NULL;

    if (data->description() == "vistalDataImageSInt3") {
        if ( vistal::Image3D<int>* image = static_cast<vistal::Image3D<int>*>( data->data() ) ) {
            if (d->SInt3Converter == NULL)
                d->SInt3Converter = new itkImage3D<int> ;
            d->SInt3Converter->SetImage3D(*image);
            d->output->setData(d->SInt3Converter->GetOutput());
        }
    }
    return d->output;
}

// /////////////////////////////////////////////////////////////////
// Type instanciation
// /////////////////////////////////////////////////////////////////

dtkAbstractDataConverter *
createVistalDataImageToItkDataImageSInt3Converter(void)
{
    return new vistalDataImageToItkDataImageSInt3Converter;
}
