// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGECONVERTERPLUGIN_H
#define ITKDATAIMAGECONVERTERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "itkDataImageConverterPluginExport.h"

class ITKDATAIMAGECONVERTERPLUGIN_EXPORT itkDataImageConverterPluginPrivate;

class ITKDATAIMAGECONVERTERPLUGIN_EXPORT itkDataImageConverterPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     itkDataImageConverterPlugin(QObject *parent = 0);
    ~itkDataImageConverterPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     itkDataImageConverterPluginPrivate *d;
};

#endif
