// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGECONVERTERPLUGINEXPORT_H
#define ITKDATAIMAGECONVERTERPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkDataImageConverterPlugin_EXPORTS
        #define ITKDATAIMAGECONVERTERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKDATAIMAGECONVERTERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKDATAIMAGECONVERTERPLUGIN_EXPORT
#endif

#endif
