// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGETOV3DDATAIMAGECONVERTER_H
#define ITKDATAIMAGETOV3DDATAIMAGECONVERTER_H

#include <dtkCore/dtkAbstractDataConverter.h>

#include "itkDataImageConverterPluginExport.h"

class itkDataImageTov3dDataImageConverterPrivate;

class ITKDATAIMAGECONVERTERPLUGIN_EXPORT itkDataImageTov3dDataImageConverter : public dtkAbstractDataConverter
{
    Q_OBJECT

public:
             itkDataImageTov3dDataImageConverter(void);
    virtual ~itkDataImageTov3dDataImageConverter(void);

    virtual QString   description(void) const;
    virtual QStringList fromTypes(void) const;
    virtual QString      toType  (void) const;


    static bool registered(void);

public slots:
    dtkAbstractData *convert(void);


private:
    itkDataImageTov3dDataImageConverterPrivate *d;
};

dtkAbstractDataConverter *createItkDataImageTov3dDataImageConverter(void);

#endif
