// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSMIDPLANEALIGNPLUGIN_H
#define VISTALPROCESSMIDPLANEALIGNPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalProcessMidPlaneAlignPluginExport.h"

class VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT vistalProcessMidPlaneAlignPluginPrivate;

class VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT vistalProcessMidPlaneAlignPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalProcessMidPlaneAlignPlugin(QObject *parent = 0);
    ~vistalProcessMidPlaneAlignPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vistalProcessMidPlaneAlignPluginPrivate *d;
};

#endif
