// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSMIDPLANEALIGN_H
#define VISTALPROCESSMIDPLANEALIGN_H

#include <dtkCore/dtkAbstractProcess.h>

#include "vistalProcessMidPlaneAlignPluginExport.h"

class vistalProcessMidPlaneAlignPrivate;

class VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT vistalProcessMidPlaneAlign : public dtkAbstractProcess
{
    Q_OBJECT

public:
             vistalProcessMidPlaneAlign(void);
    virtual ~vistalProcessMidPlaneAlign(void);

    virtual QString description(void) const;

    static bool registered(void);


signals:
    void success(void);
    void failure(void);


public slots:

    void setInput(dtkAbstractData *data);
    void setParameter(double  data, int channel);
    int update(void);
    dtkAbstractData *output(void);


private:
    vistalProcessMidPlaneAlignPrivate *d;
};

dtkAbstractProcess *createVistalProcessMidPlaneAlign(void);

#endif
