// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSMIDPLANEALIGNPLUGINEXPORT_H
#define VISTALPROCESSMIDPLANEALIGNPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalProcessMidPlaneAlignPlugin_EXPORTS
        #define VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALPROCESSMIDPLANEALIGNPLUGIN_EXPORT
#endif

#endif
