// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSBIASREMOVALPLUGIN_H
#define VISTALPROCESSBIASREMOVALPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalProcessBiasRemovalPluginExport.h"

class vistalProcessBiasRemovalPluginPrivate;
class vistalProcessBiasRemovalPlugin;

class VISTALPROCESSDENOISINGPLUGIN_EXPORT vistalProcessBiasRemovalPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalProcessBiasRemovalPlugin(QObject *parent = 0);
    vistalProcessBiasRemovalPlugin(void);
	
	virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vistalProcessBiasRemovalPluginPrivate *d;
};

#endif
