// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSBIASREMOVALPLUGINEXPORT_H
#define VISTALPROCESSBIASREMOVALPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalProcessBiasRemovalPlugin_EXPORTS
        #define VISTALPROCESSDENOISINGPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALPROCESSDENOISINGPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALPROCESSDENOISINGPLUGIN_EXPORT
#endif

#endif
