// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSGRAPHCUTSEG_H
#define VISTALPROCESSGRAPHCUTSEG_H

#include <dtkCore/dtkAbstractProcess.h>

#include "vistalProcessGraphCutSegPluginExport.h"

class vistalProcessGraphCutSegPrivate;

// /////////////////////////////////////////////////////////////////
// vistalProcessGraphCutSeg interface
// /////////////////////////////////////////////////////////////////

class VISTALPROCESSGRAPHCUTSEGPLUGIN_EXPORT vistalProcessGraphCutSeg : public dtkAbstractProcess
{
    Q_OBJECT

public:
             vistalProcessGraphCutSeg(void);
             vistalProcessGraphCutSeg(const vistalProcessGraphCutSeg& other);
    virtual ~vistalProcessGraphCutSeg(void);

public:
    vistalProcessGraphCutSeg& operator = (const vistalProcessGraphCutSeg& other);

public:
    virtual QString description(void) const;
    virtual QString identifier(void) const;

    static bool registered(void);

private:
    DTK_DECLARE_PRIVATE(vistalProcessGraphCutSeg);
};

dtkAbstractProcess *createVistalProcessGraphCutSeg(void);

#endif
