// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALPROCESSGRAPHCUTSEGPLUGIN_H
#define VISTALPROCESSGRAPHCUTSEGPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalProcessGraphCutSegPluginExport.h"

class VISTALPROCESSGRAPHCUTSEGPLUGIN_EXPORT vistalProcessGraphCutSegPluginPrivate;

// /////////////////////////////////////////////////////////////////
// vistalProcessGraphCutSegPlugin interface
// /////////////////////////////////////////////////////////////////

class VISTALPROCESSGRAPHCUTSEGPLUGIN_EXPORT vistalProcessGraphCutSegPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalProcessGraphCutSegPlugin(QObject *parent = 0);
     vistalProcessGraphCutSegPlugin(const vistalProcessGraphCutSegPlugin& other);
    ~vistalProcessGraphCutSegPlugin(void);

public:
    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
    DTK_DECLARE_PRIVATE(vistalProcessGraphCutSegPlugin);
};

#endif
