// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ANIMADENSEBMREGISTRATIONPLUGINEXPORT_H
#define ANIMADENSEBMREGISTRATIONPLUGINEXPORT_H

#ifdef WIN32
    #ifdef animaDenseBMRegistrationPlugin_EXPORTS
        #define ANIMADENSEBMREGISTRATIONPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ANIMADENSEBMREGISTRATIONPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ANIMADENSEBMREGISTRATIONPLUGIN_EXPORT
#endif

#endif
