// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <medRegistrationAbstractToolBox.h>
#include "animaDenseBMRegistrationPluginExport.h"

class animaDenseBMRegistrationToolBoxPrivate;

class ANIMADENSEBMREGISTRATIONPLUGIN_EXPORT animaDenseBMRegistrationToolBox : public medRegistrationAbstractToolBox
{
    Q_OBJECT
    
public:
    animaDenseBMRegistrationToolBox(QWidget *parent = 0);
    ~animaDenseBMRegistrationToolBox(void);
    
public:
    static bool registered(void);
    
public slots:
    void run(void);
    void updateBMOptimizerParams(int);
    void updateBMTransformParams(int);
    void updateBMAgregatorParams(int);
    void updateDamUsage(int);
    
private:
    animaDenseBMRegistrationToolBoxPrivate *d;
};
