// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEDOUBLE3_H
#define VISTALDATAIMAGEDOUBLE3_H

#include <medAbstractImageData.h>

#include <vistalDataImagePluginExport.h>

class vistalDataImageDouble3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageDouble3 : public medAbstractImageData
{
    Q_OBJECT
    MED_DATA_INTERFACE("Vistal Image (Double3)",
                       "Vistal Image (Double3)")

public:
             vistalDataImageDouble3(void);
    virtual ~vistalDataImageDouble3(void);

    static bool registered(void);
	
public slots:
    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

	int minRangeValue(void);
	int maxRangeValue(void);
	
private:
    vistalDataImageDouble3Private *d;
};

#endif
