// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGESCHAR3_H
#define VISTALDATAIMAGESCHAR3_H

#include <dtkCore/dtkAbstractDataImage.h>

#include "vistalDataImagePluginExport.h"

class vistalDataImageSChar3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageSChar3 : public dtkAbstractDataImage
{
    Q_OBJECT

public:
             vistalDataImageSChar3(void);
    virtual ~vistalDataImageSChar3(void);

    virtual QString description(void) const;

    static bool registered(void);
	
		virtual QImage &thumbnail(void)   const;
		virtual QList<QImage> &thumbnails (void) const;
	
public slots:
    // derived from dtkAbstractData

    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

	int minRangeValue(void);
	int maxRangeValue(void);
	
private:
    vistalDataImageSChar3Private *d;
};

dtkAbstractData *createVistalDataImageSChar3(void);

#endif
