// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEUINT3_H
#define VISTALDATAIMAGEUINT3_H

#include <medAbstractImageData.h>

#include <vistalDataImagePluginExport.h>

class vistalDataImageUInt3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageUInt3 : public medAbstractImageData
{
    Q_OBJECT
    MED_DATA_INTERFACE("Vistal Image (UInt3)",
                       "Vistal Image (UInt3)")

public:
             vistalDataImageUInt3(void);
    virtual ~vistalDataImageUInt3(void);

    static bool registered(void);
	
public slots:
    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

	int minRangeValue(void);
	int maxRangeValue(void);
	
private:
    vistalDataImageUInt3Private *d;
};

#endif
