// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "vistalDataImageUChar3.h"
#include "vistalDataImageUShort3.h"
#include "vistalDataImageSShort3.h"
#include "vistalDataImagePlugin.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// vistalDataImagePluginPrivate
// /////////////////////////////////////////////////////////////////

class vistalDataImagePluginPrivate
{
    public:
        // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// vistalDataImagePlugin
// /////////////////////////////////////////////////////////////////

vistalDataImagePlugin::vistalDataImagePlugin(QObject *parent) :
    dtkPlugin(parent), d(new vistalDataImagePluginPrivate)
{

}

vistalDataImagePlugin::~vistalDataImagePlugin(void)
{
    delete d;

    d = NULL;
}

bool
vistalDataImagePlugin::initialize(void)
{
	if (!vistalDataImageUChar3::registered())
		dtkWarning() << "Unable to register vistalDataImageUChar3 type";
	
	if (!vistalDataImageUShort3::registered())
		dtkWarning() << "Unable to register vistalDataImageUShort3 type";
	
	if (!vistalDataImageSShort3::registered())
		dtkWarning() << "Unable to register vistalDataImageSShort3 type";
	
	return true;
}

bool
vistalDataImagePlugin::uninitialize(void)
{
    return true;
}

QString
vistalDataImagePlugin::name(void) const
{
    return "vistalDataImagePlugin";
}

QString
vistalDataImagePlugin::description(void) const
{
    return "Vistal data image plugin";
}

QStringList
vistalDataImagePlugin::tags(void) const
{
    return QStringList() << "vistal" << "image" << "data";
}

QStringList
vistalDataImagePlugin::types(void) const
{
    return QStringList() << "vistalDataImageUChar3" << "vistalDataImageUShort3" << "vistalDataImageSShort3";
}

Q_EXPORT_PLUGIN2(vistalDataImagePlugin, vistalDataImagePlugin)
