// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEUCHAR3_H
#define VISTALDATAIMAGEUCHAR3_H

#include <medAbstractImageData.h>

#include <vistalDataImagePluginExport.h>

class vistalDataImageUChar3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageUChar3 : public medAbstractImageData
{
    Q_OBJECT
    MED_DATA_INTERFACE("Vistal Image (UChar3)",
                       "Vistal Image (UChar3)")

public:
             vistalDataImageUChar3(void);
    virtual ~vistalDataImageUChar3(void);

    static bool registered(void);
	
public slots:
    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

	int minRangeValue(void);
	int maxRangeValue(void);
	
private:
    vistalDataImageUChar3Private *d;
};

#endif
