// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEFLOAT3_H
#define VISTALDATAIMAGEFLOAT3_H

#include <dtkCore/dtkAbstractDataImage.h>

#include "vistalDataImagePluginExport.h"

class vistalDataImageFloat3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageFloat3 : public dtkAbstractData
{
    Q_OBJECT

public:
             vistalDataImageFloat3(void);
    virtual ~vistalDataImageFloat3(void);

    virtual QString description(void) const;

    static bool registered(void);

public slots:
    // derived from dtkAbstractData

    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

private:
    vistalDataImageFloat3Private *d;
};

dtkAbstractData *createVistalDataImageFloat3(void);

#endif
