// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEPLUGINEXPORT_H
#define VISTALDATAIMAGEPLUGINEXPORT_H

#ifdef WIN32
    #ifdef vistalDataImagePlugin_EXPORTS
        #define VISTALDATAIMAGEPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define VISTALDATAIMAGEPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define VISTALDATAIMAGEPLUGIN_EXPORT
#endif

#endif
