// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "Image3D.hh"
#include "vistalDataImageUShort3.h"

#include <dtkCore/dtkAbstractDataFactory.h>

// /////////////////////////////////////////////////////////////////
// vistalDataImageUShort3Private
// /////////////////////////////////////////////////////////////////

class vistalDataImageUShort3Private
{
public:
  vistal::Image3D<unsigned short> * image;
};

// /////////////////////////////////////////////////////////////////
// vistalDataImageUShort3
// /////////////////////////////////////////////////////////////////

vistalDataImageUShort3::vistalDataImageUShort3(void) : dtkAbstractDataImage(), d(new vistalDataImageUShort3Private)
{
  d->image = 0;
}

vistalDataImageUShort3::~vistalDataImageUShort3(void)
{
	if (d->image)
		delete d->image;
	
	delete d;
	d = 0;
}

bool vistalDataImageUShort3::registered(void)
{
    return dtkAbstractDataFactory::instance()->registerDataType("vistalDataImageUShort3", createVistalDataImageUShort3);
}

QString vistalDataImageUShort3::description(void) const
{
    return "vistalDataImageUShort3";
}

void *vistalDataImageUShort3::data()
{
  return d->image;
}

void *vistalDataImageUShort3::output()
{
	return d->image;
}

void vistalDataImageUShort3::setData(void* data)
{
  d->image = static_cast<vistal::Image3D<unsigned short> *> (data);
}

int vistalDataImageUShort3::xDimension(void)
{
  if (d->image != NULL)
    return d->image->nbx;
  else
    return -1;
}

int vistalDataImageUShort3::yDimension(void)
{
  if (d->image != NULL)
    return d->image->nby;
  else
    return -1;
}

int vistalDataImageUShort3::zDimension(void)
{
  if (d->image != NULL)
    return d->image->nbz;
  else
    return -1;
}

int vistalDataImageUShort3::tDimension(void)
{
  if (d->image != NULL)
    return d->image->nbt;
  else
    return -1;
}


// /////////////////////////////////////////////////////////////////
// Type instanciation
// /////////////////////////////////////////////////////////////////

dtkAbstractData *createVistalDataImageUShort3(void)
{
    return new vistalDataImageUShort3;
}
