// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEPLUGIN_H
#define VISTALDATAIMAGEPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vistalDataImagePluginExport.h"

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImagePluginPrivate;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImagePlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vistalDataImagePlugin(QObject *parent = 0);
    ~vistalDataImagePlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vistalDataImagePluginPrivate *d;
};

#endif
