// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEUCHAR3_H
#define VISTALDATAIMAGEUCHAR3_H

#include <dtkCore/dtkAbstractDataImage.h>

#include "vistalDataImagePluginExport.h"

class vistalDataImageUChar3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageUChar3 : public dtkAbstractDataImage
{
    Q_OBJECT

public:
             vistalDataImageUChar3(void);
    virtual ~vistalDataImageUChar3(void);

    virtual QString description(void) const;

    static bool registered(void);

public slots:
    // derived from dtkAbstractData
    
    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

private:
    vistalDataImageUChar3Private *d;
};

dtkAbstractData *createVistalDataImageUChar3(void);

#endif
