// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "Image3D.hh"
#include "vistalDataImageFloat3.h"

#include <dtkCore/dtkAbstractDataFactory.h>

// /////////////////////////////////////////////////////////////////
// vistalDataImageFloat3Private
// /////////////////////////////////////////////////////////////////

class vistalDataImageFloat3Private
{
public:
  vistal::Image3D<float> * image;
};

// /////////////////////////////////////////////////////////////////
// vistalDataImageFloat3
// /////////////////////////////////////////////////////////////////

vistalDataImageFloat3::vistalDataImageFloat3(void) : dtkAbstractDataImage(), d(new vistalDataImageFloat3Private)
{
  d->image = 0;
}

vistalDataImageFloat3::~vistalDataImageFloat3(void)
{
	if (d->image)
		delete d->image;
	
	delete d;
	d = 0;
}

bool vistalDataImageFloat3::registered(void)
{
    return dtkAbstractDataFactory::instance()->registerDataType("vistalDataImageFloat3", createVistalDataImageFloat3);
}

QString vistalDataImageFloat3::description(void) const
{
    return "vistalDataImageFloat3";
}

void *vistalDataImageFloat3::data()
{
  return d->image;
}

void *vistalDataImageFloat3::output()
{
	return d->image;
}

void vistalDataImageFloat3::setData(void* data)
{
  d->image = static_cast<vistal::Image3D<float> *> (data);
}

int vistalDataImageFloat3::xDimension(void)
{
  if (d->image != NULL)
    return d->image->nbx;
  else
    return -1;
}

int vistalDataImageFloat3::yDimension(void)
{
  if (d->image != NULL)
    return d->image->nby;
  else
    return -1;
}

int vistalDataImageFloat3::zDimension(void)
{
  if (d->image != NULL)
    return d->image->nbz;
  else
    return -1;
}

int vistalDataImageFloat3::tDimension(void)
{
  if (d->image != NULL)
    return d->image->nbt;
  else
    return -1;
}


// /////////////////////////////////////////////////////////////////
// Type instanciation
// /////////////////////////////////////////////////////////////////

dtkAbstractData *createVistalDataImageFloat3(void)
{
    return new vistalDataImageFloat3;
}
