// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VISTALDATAIMAGEUINT3_H
#define VISTALDATAIMAGEUINT3_H

#include <dtkCore/dtkAbstractDataImage.h>

#include "vistalDataImagePluginExport.h"

class vistalDataImageUInt3Private;

class VISTALDATAIMAGEPLUGIN_EXPORT vistalDataImageUInt3 : public dtkAbstractDataImage
{
    Q_OBJECT

public:
             vistalDataImageUInt3(void);
    virtual ~vistalDataImageUInt3(void);

    virtual QString description(void) const;

    static bool registered(void);
	
		virtual QImage &thumbnail(void)   const;
		virtual QList<QImage> &thumbnails (void) const;
	
public slots:
    // derived from dtkAbstractData

    void *output(void);
    void *data(void);
    void setData(void* data);

 public:
    int xDimension(void);
    int yDimension(void);
    int zDimension(void);
    int tDimension(void);

private:
    vistalDataImageUInt3Private *d;
};

dtkAbstractData *createVistalDataImageUInt3(void);

#endif
